CREATE TABLE TB_AREA(
	AREA_ID INT(10) NOT NULL AUTO_INCREMENT,
	ARER_NAME VARCHAR(200) NOT NULL,
	PRIORITY INT(2) NOT NULL DEFAULT 0,
	CREATE_TIME DATETIME DEFAULT NULL,
	LAST_EDIT_TIME DATETIME DEFAULT NULL,
	PRIMARY KEY (AREA_ID),
	UNIQUE KEY UK_AREA(ARER_NAME)	
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

CREATE TABLE TB_PERSONINFO(
	USER_ID INT(10) NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(200) NOT NULL,
	PROFILEIMG VARCHAR(1000) NOT NULL,
	EMAIL VARCHAR(1000) NOT NULL,
	GENDER INT(2) NOT NULL DEFAULT 1,
	ENABLESTATUS INT(2) NOT NULL DEFAULT 1 COMMENT '0:禁止使用本商城  1:允许使用本商城',
	USERTYPE INT(2) NOT NULL DEFAULT 1 COMMENT '1:顾客  2:店家   3:管理员',
	CREATE_TIME DATETIME DEFAULT NULL,
	LAST_EDIT_TIME DATETIME DEFAULT NULL,
	PRIMARY KEY (USER_ID)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

